version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '80:80'
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - db
    db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_ROOT_HOST: mysql
            MYSQL_DATABASE: fitness-park
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}']
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
        depends_on:
            - db
